### ISSUE TITLE
Binary for Linux 32 bit X86

### ISSUE THREAD

**Issue by surereddy** [hverr/udptun#5]
hello sir can u please give binary for linux 32bit X86 kindly

**Comment by hverr** [comment]
I'm sorry, but I don't have a 32-bit system available at the moment. However, if you really need it, it should be very easy to create your own binary by following the build instructions.

**Comment by surereddy** [comment]
Hello i couldn't build sir.Can you please provide me

**Comment by surereddy** [comment]
opam install async_ssl
[WARNING] Running as root is not recommended
[ERROR] No package named async_ssl found.

udptun# ./configure
Cannot find file topfind.
Unknown directive `require'.
